# Generated by Django 4.1 on 2022-09-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='release_date',
            new_name='Release_date',
        ),
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='review',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='watched',
            new_name='Watched',
        ),
    ]
