# Generated by Django 4.1 on 2022-11-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_mywatchlist_title_alter_mywatchlist_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='Watched',
            field=models.BooleanField(),
        ),
    ]
